config/routes.rb
Rails.application.routes.draw do

  get 'access_codes/new'

  get 'access_codes/create'

  get 'access_codes/destroy'

  get 'replies/create'

  get 'replies/destroy'


  root 'application#front'   
  get  '/contact', :to =>      'static_pages#contact'
  get  '/help', :to =>         'static_pages#help'
  get  '/about', :to =>        'static_pages#about'
  get  '/home', :to =>         'static_pages#home'
  get 'calendar' =>            'static_pages#calendar'
  get  '/login', :to =>        'sessions#new'
  post '/login', :to =>        'sessions#create'
  delete '/logout', :to =>     'sessions#destroy'
  get  '/signup',:to =>        'users#new'
  post '/signup',:to =>        'users#create' 
  get '/access_codes' =>       'access_codes#new'
  get '/deactivate' =>         'users#deactivate'
  post '/relationships/:id' => 'relationships#create'
  get '/search' =>             'posts#search'


  resources :users do
    member do
      get :unfollowing
    end
  end
  get  '/settings', :to =>  'users#settings'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts,               only: [:create, :destroy, :show]
  resources :replies,             only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :access_codes,        only: [:new, :create , :destroy]
  resources :pins,                only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token, :code
   
  before_save { self.email = email.downcase }
  before_create :create_activation_digest
  validates :password, presence: true, length: { minimum: 6, maximum: 25 }, allow_nil: true 
  validates :name, presence: true, length: { maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates(:email, presence: true, 
                    length: {maximum: 255}, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false })
  has_secure_password
  has_many :posts, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :pins, dependent: :destroy
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "unfollower_id",
                                   dependent:   :destroy
  has_many :unfollowing, through: :active_relationships, source: :unfollowed
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "unfollowed_id",
                                   dependent:   :destroy
  has_many :unfollowers, through: :passive_relationships, source: :unfollower

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end


  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def feed
    unfollowing_ids = "SELECT unfollowed_id FROM relationships
                       WHERE  unfollower_id = :user_id"
    admin_pinned_posts +
    user_pinned_posts + 
    Post.where("user_id NOT IN (#{unfollowing_ids})", user_id: id)
  end

  def profile_feed
    replied_to = "SELECT post_id FROM replies
                  WHERE user_id = :user_id"
    user_pinned_posts + Post.where("user_id = :user_id OR id IN (#{replied_to})", user_id: id)
  end

  def unfollow(other_user)
    unfollowing << other_user
  end

  def follow(other_user)
    unfollowing.delete(other_user)
  end

  def following?(other_user)
    !unfollowing.include?(other_user)
  end

  private
  
    def create_activation_digest
      self.activation_token =  User.new_token
      self.activation_digest = User.digest(activation_token)
    end

    def user_pinned_posts
      user_pins = Pin.where('user_id = ?', id)
      user_pinned_post_ids = user_pins.map{ |p| p.post_id }
      posts = Post.find user_pinned_post_ids
      posts.each do |post|
        post.user_pinned = true
        post.title = post.title.to_s +  " (pinned)"
      end
      return posts
    end

    def admin_pinned_posts
      admin_pins = Pin.where('user_id = ?', 1)#assumes only one admin
      admin_pinned_post_ids = admin_pins.map{ |p| p.post_id }
      posts = Post.find admin_pinned_post_ids
      posts.each do |post|
        post.admin_pinned = true
        post.title = post.title.to_s + " (pinned by admin)"
      end
      return posts
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_logged_in, only: [:edit, :update, :index, :show, :unfollowing, :deactivate, :destroy]
  before_action :correct_user,   only: [:edit, :update, :unfollowing]
  before_action :delete_rights,  only: :destroy

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
    @posts = @user.profile_feed.paginate(page: params[:page])
    @reply = current_user.replies.build if @posts
    store_location
  end

  def new
    @user = User.new
  end

  def create
    access_code = user_params[:code]
    @user = User.new(user_params)
    if correct_code(access_code) && @user.save
      @user.send_activation_email
      flash[:success] = "Please check your email to activate your account"
      redirect_to root_url
    else
      render 'new' 
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile edited succesfully" 
      redirect_to @user
    else
      render 'edit'
    end
  end

  def deactivate
    @user = current_user
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def settings
    @user = current_user
  end

  def unfollowing
    @users = @user.unfollowing.paginate(page: params[:page])
  end

  private 
  
    def user_params
      params.require(:user).permit(:name, 
                                   :email, 
                                   :password, 
                                   :password_confirmation,
                                   :code)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def delete_rights
      @user = User.find(params[:id])
      redirect_to(login_url) unless current_user && (current_user.admin? || current_user?(@user))
    end

    def correct_code(access_code)
      if access_code && ((AccessCode.all.map { |c| c.code }).include? access_code)
        true
      else
        @user.errors.add(:activation_code, "is invalid")
        false
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.haml
- Rails.logger.info "delete/refollow rendered"
= form_for(current_user.active_relationships.find_by(unfollowed_id: @user.id), 
  html: { method: :delete }, remote: true) do |f|                                          
  = f.submit "follow", :class => 'relationship'

app/views/users/_relationship.html.haml
-unless current_user?(@user)
  #follow_form
    -if current_user.following?(@user)
      =render 'unfollow'
    -else
      =render 'follow'

app/views/users/_unfollow.html.haml
- Rails.logger.info "post/unfollow rendered"
= form_for(current_user.active_relationships.build, :url => url_for( :controller => 'relationships', :action => :create) , remote: true, :html => { :class => "unfollow_form_#{@user.id}"}) do |f|
  %div= hidden_field_tag :unfollowed_id, @user.id
  = f.submit "unfollow", :class => 'relationship'

app/views/users/_user.html.haml
-@user = user
.mat-card
  = link_to user, :class => "user-name" do
    %h4
      = user.name
  %p
    = "email: #{user.email}"
  -if current_user.admin? && !current_user?(user)
    =link_to "delete", user, method: :delete, data: { confirm: "Are you sure?"}, class: "link"
  =render 'relationship'

app/views/users/deactivate.html.haml
=content_for(:title, "Deactivate")
.mat-card
  %h3= "Deactivate"
  %p Clicking the link below will deactivate your account. This action is irreversable. All of your user settings, information, posts, and replies will be destroyed. 
  =link_to "deactivate", @user, method: :delete, data: {confirm: "Are you sure?"}, class: "link"

app/views/users/edit.html.haml
=content_for(:title, "Edit your profile")
.mat-card
  %h3 Edit your profile
  = form_for(@user) do |f|
    = render 'shared/error_messages', object: f.object
    
    = f.label :name
    = f.text_field :name, :class => 'text-input', autofocus: true
    
    = f.label :email
    = f.email_field :email, :class => 'text-input'

    = f.submit "Save Changes", class: "form-submit"

app/views/users/index.html.haml
=content_for(:title, "All users")
.mat-card
  %h2{:style => "text-align: center; margin: 0;"}
    Users
=will_paginate inner_window: 2, outer_window: 0, :previous_label => 'Back', :next_label => 'Next', :class => 'paginate'
=render @users
=will_paginate inner_window: 2, outer_window: 0, :previous_label => 'Back', :next_label => 'Next', :class => 'paginate'

app/views/users/new.html.haml
=content_for(:title, "Sign up")
.mat-card
  %h3= "Sign-up"
  = form_for(@user) do |f| 
    = render 'shared/error_messages', object: f.object

    = f.label :name
    = f.text_field :name, :class => 'text-input', autofocus: true

    = f.label :email 
    = f.email_field :email, :class => 'text-input'

    = f.label :password 
    = f.password_field :password, :class => 'text-input'

    = f.label :password_confirmation 
    = f.password_field :password_confirmation, :class => 'text-input'

    = f.label :access_code
    = f.text_field :code, :class => 'text-input'

    = f.submit "Sign up", class: "form-submit"

app/views/users/settings.html.haml
=content_for(:title, "Settings")
.mat-card
  %h3= "Settings"
  %p=link_to "Manage who you follow", unfollowing_user_path(@user)
  %p=link_to "Deactivate account", '/deactivate'

app/views/users/show.html.haml
=content_for(:title, @user.name)
.mat-card
  %h3= @user.name
  %p This is the infomation page about user #{@user.id}
  %p= "email: #{@user.email}"
  =render 'relationship'
-if @user.posts.any?
  %ol.post-list
    =render @posts
  =will_paginate @posts, inner_window: 2, outer_window: 0, :previous_label => 'Back', :next_label => 'Next', :class => 'paginate'
   

app/views/users/unfollowing.html.haml
=content_for(:title, "Unfollowed")
.mat-card
  %h3= "Unfollowed Users"
  %p
    You have unfollowed
    =succeed " users' activity from your news feed. To re-follow a user just click the 'follow' link next to their name." do
      %strong#unfollowing= @users.count
=render @users
=will_paginate inner_window: 2, outer_window: 0, :previous_label => 'Back', :next_label => 'Next', :class => 'paginate'