config/routes.rb
Rails.application.routes.draw do

  get 'access_codes/new'

  get 'access_codes/create'

  get 'access_codes/destroy'

  get 'replies/create'

  get 'replies/destroy'


  root 'application#front'   
  get  '/contact', :to =>      'static_pages#contact'
  get  '/help', :to =>         'static_pages#help'
  get  '/about', :to =>        'static_pages#about'
  get  '/home', :to =>         'static_pages#home'
  get 'calendar' =>            'static_pages#calendar'
  get  '/login', :to =>        'sessions#new'
  post '/login', :to =>        'sessions#create'
  delete '/logout', :to =>     'sessions#destroy'
  get  '/signup',:to =>        'users#new'
  post '/signup',:to =>        'users#create' 
  get '/access_codes' =>       'access_codes#new'
  get '/deactivate' =>         'users#deactivate'
  post '/relationships/:id' => 'relationships#create'
  get '/search' =>             'posts#search'


  resources :users do
    member do
      get :unfollowing
    end
  end
  get  '/settings', :to =>  'users#settings'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts,               only: [:create, :destroy, :show]
  resources :replies,             only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :access_codes,        only: [:new, :create , :destroy]
  resources :pins,                only: [:create, :destroy]

end

app/models/post.rb
class Post < ApplicationRecord
  attr_accessor :admin_pinned, :user_pinned

  belongs_to :user
  has_many :replies, dependent: :destroy 
  has_many :pins, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, length: { maximum: 3000 }
  validates :content, presence: { if: -> { picture.blank? } }
  validates :picture, presence: { if: -> { content.blank? } }
  validate :picture_size

  validates :title, length: { maximum: 100 }
  validates_presence_of :title, :if => :event?

  validates_presence_of :event_time, :if  => :event?

  validates :event_location, length: { maximum: 100 }, :if => :event?
  validates_presence_of :event_location, :if => :event?
 
  #validate the event? if location & time present
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :user_logged_in, only: [:create, :destroy, :show, :search] 
  before_action :delete_rights,  only: :destroy

  def show
    @post = Post.find(params[:id])
    @reply = current_user.replies.build if @post
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.event = true unless @post.event_location.nil? || 
                              @post.event_location.empty? || 
                              @post.event_time.nil?
    if @post.save
      @post.event? ? flash[:success] = "Event posted!" 
                   : flash[:success] = "Post created!"
      redirect_to '/home'        
    else
      flash[:danger] = "Invalid post"
      respond_to do |format|
        format.html { redirect_to '/home' }
        format.js
      end
    end
  end

  def destroy 
    @post.destroy
    flash[:success] = "Post removed"
    redirect_to request.referrer || root_url
  end

  def search
    @term = params[:search][:term]
    @results = Post.left_outer_joins(:replies).distinct.where("posts.title LIKE :term OR posts.content LIKE :term OR replies.content LIKE :term", 
                 term: "%#{@term}%").paginate(page: params[:page])
    @reply = Reply.new
  end

  private
  
    def post_params
      params.require(:post).permit( :title,
                                    :content, 
                                    :picture,
                                    :event_time,
                                    :event_location)
    end

    def delete_rights
      @post = Post.find_by(id: params[:id])
      redirect_to root_url unless !@post.nil? && (current_user.admin? || (current_user == @post.user))
    end

end

app/helpers/posts_helper.rb
module PostsHelper
 
  def events(start_date, end_date)
    Post.where("event_time BETWEEN ? AND ? AND event= ?", start_date, end_date, true)
  end

end

app/views/posts/_pin.html.haml
-post = locals[:post]
=link_to "pin", pins_path(post_id: post.id), method: :post 

app/views/posts/_post.html.haml
.mat-card
  -if post.title?
    %h3= post.title
  %span.post-title
    =link_to post.user.name, post.user
  %span.timestamp{:style => "display: inline;"}
    %small  
      =time_ago_in_words(post.created_at)
  -if post.event?
    -Time::DATE_FORMATS[:custom_long_ordinal] = "%B %e, %l:%M %p"
    .event-info= "Where: #{post.event_location}"
    .event-info= "When: #{post.event_time.to_formatted_s(:custom_long_ordinal)}"
  -term = (defined? locals) ? locals[:term] : nil
  =render 'shared/content', :locals => { :content => post.content, :term => term }
  =image_tag(post.picture.url, :class => "picture") if post.picture?
  -if current_user?(post.user) || current_user.admin?
    %span
      %small
        =link_to "delete", post, method: :delete, data: { confirm: "Are you sure?"}
  //fix this so we're not looking up pins twice
  -unless post.admin_pinned && !current_user.admin?
    %span
      %small 
        -pin = Pin.where('user_id = ? AND post_id = ?', current_user.id, post.id).first
        -if pin.nil?
          =render 'posts/pin', :locals => { :post => post }
        -else
          =render 'posts/unpin', :locals => { :pin => pin } 
  =render Reply.where(post: post), :locals => { :term => term } 
  =render 'shared/reply_form', post: post 

app/views/posts/_unpin.html.haml
-pin = locals[:pin]
=link_to "unpin", pin_path(id: pin.id), method: :delete

app/views/posts/create.js.erb
<% @object = @post %>
if ($("#error_explanation").length === 0) {
  $("<%= escape_javascript(render('shared/error_messages')) %>").insertBefore("#new_post");
} else { 
  $("#error_explanation").html("<%= escape_javascript(render('shared/error_messages')) %>");
}

app/views/posts/search.html.haml
=content_for(:title, "Search Results")
.mat-card
  %span="Showing #{@results.count} results for: \"#{@term}\""
=render @results, :locals => { :term => @term }
=will_paginate @results, inner_window: 2, outer_window: 0, :previous_label => 'Back', :next_label => 'Next', :class => 'paginate'

app/views/posts/show.html.haml
=content_for(:title, (@post.title || "Post #{@post.id}"))
=render @post