config/routes.rb
Rails.application.routes.draw do

  get 'access_codes/new'

  get 'access_codes/create'

  get 'access_codes/destroy'

  get 'replies/create'

  get 'replies/destroy'


  root 'application#front'   
  get  '/contact', :to =>      'static_pages#contact'
  get  '/help', :to =>         'static_pages#help'
  get  '/about', :to =>        'static_pages#about'
  get  '/home', :to =>         'static_pages#home'
  get 'calendar' =>            'static_pages#calendar'
  get  '/login', :to =>        'sessions#new'
  post '/login', :to =>        'sessions#create'
  delete '/logout', :to =>     'sessions#destroy'
  get  '/signup',:to =>        'users#new'
  post '/signup',:to =>        'users#create' 
  get '/access_codes' =>       'access_codes#new'
  get '/deactivate' =>         'users#deactivate'
  post '/relationships/:id' => 'relationships#create'
  get '/search' =>             'posts#search'


  resources :users do
    member do
      get :unfollowing
    end
  end
  get  '/settings', :to =>  'users#settings'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts,               only: [:create, :destroy, :show]
  resources :replies,             only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :access_codes,        only: [:new, :create , :destroy]
  resources :pins,                only: [:create, :destroy]

end

app/views/layouts/_footer.html.haml
%footer
  %small
    This is the #{APP_NAME}.
  %ul
    %li= link_to "Help",    help_url 
    %li= link_to "About",   about_url
    %li= link_to "Contact", contact_url 

app/views/layouts/_header.html.haml
%header
  = image_tag "4869_rice_owls-primary_on_dark-2010.jpg", height: 35, width: 42, :class => "logo", :id => "logo1"
  =link_to APP_NAME, root_path, :class => "logo", :id => 'logo2'
  .right-align
    -if logged_in? 
      =form_for(:search, url: search_path, html: {:class => "search-form", :method => 'GET'}) do |f|
        = button_tag( :class => 'search-submit') do 
          = content_tag(:i, "search", class: "material-icons")
        = f.text_field :term, :class => 'search-input', placeholder: "search"
      
    =link_to "☰", '', id: "burger", class: "hamburger noselect"
  %ul#nav-hidden
    -if logged_in? 
      %li
        =link_to "Home", "/home"
      %li
        =link_to "Users", users_path
      %li
        =link_to "Profile", user_path(current_user)
      %li
        =link_to "Calendar", "/calendar"
      %li
        =link_to "Edit profile", edit_user_path(current_user) 
      %li
        =link_to "Settings", settings_url
      -if current_user.admin?
        %li
          =link_to "Access Codes", "/access_codes"
      %li
        =link_to "Log out", logout_url, :method => "delete"
    -else
      %li
        =link_to "Log in", "/login"
      %li
        =link_to "Sign Up", "/signup" 
      %li
        =link_to "Home", '/'

app/views/layouts/_ie_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= "#{APP_NAME} | " << yield(:title)
    %meta{ :content => 'width=device-width, initial-scale=1 user-scalable=0', :name => 'viewport' } 
    %link{ :href => 'https://fonts.googleapis.com/css?family=Roboto:400,900', :rel => 'stylesheet' } 
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/ie_shim'
    -imageclass = "image-#{rand(5)}"
    :css
      body {
        font-family: 'Roboto';
      } 
  %body{:class => imageclass }
    =render 'layouts/header'
    .push
    - flash.each do |message_type, message| 
      .mat-card.alert{ :class => "alert-#{message_type}"}=message
    =yield 

    -if Rails.env.development? 
      .mat-card 
        =debug(params)
    =render 'layouts/footer'   